version: '3.8'

services:
  budgee_db:
    container_name: budgee_db
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: budgee
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

volumes:
  postgres-data: null
